server:
  port: 9998
spring:
  mvc:
    servlet:
      load-on-startup: 1
  user:
    oauth:
      clientId: fort
      clientSecret: j1d1sec.c0m
      checkTokenUrl: http://dev.server:8080/fort-auth-server/oauth/check_token
    server:
      datasource:
        url: jdbc:mysql://dev.server:3306/new_fort?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
        username: root
        password: Zhigongzhang1991@
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 100
        maxWait: 1000
        poolPreparedStatements: true
        defaultAutoCommit: true
        removeAbandoned: true
        removeAbandonedTimeout: 60
        logAbandoned: true
        validationQuery: select 1 from dual
        testOnBorrow: true
logging:
  config: classpath:log4j2.xml