server:
  port: 9998
spring:
  user:
    oauth:
      clientId: fort
      clientSecret: j1d1sec.c0m
      checkTokenUrl: http://dev.server:9999/oauth/check_token
    server:
      datasource:
        url: jdbc:mysql://dev.server:3306/new_fort?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
        username: root
        password: Zhigongzhang1991@
        driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:log4j2.xml